name: PHP

env:
  COMPOSE_USER: runner

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  coding-standards:
    name: PHP - Check Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Create docker network
        run: |
          docker network create frontend

      - run: |
          docker compose run --rm phpfpm composer install
          docker compose run --rm phpfpm vendor/bin/php-cs-fixer fix --dry-run --diff
          docker compose run --rm phpfpm vendor/bin/twig-cs-fixer lint

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Create docker network
        run: |
          docker network create frontend

      - run: |
          docker compose run --rm phpfpm composer install
          docker compose run --rm phpfpm vendor/bin/phpstan analyse . --configuration=phpstan.neon
